:: build the shell
cl ^
    /O2 ^
    -DSQLITE_ENABLE_COLUMN_METADATA ^
    -DSQLITE_ENABLE_DBSTAT_VTAB ^
    -DSQLITE_ENABLE_DESERIALIZE ^
    -DSQLITE_ENABLE_EXPLAIN_COMMENTS ^
    -DSQLITE_ENABLE_FTS3 ^
    -DSQLITE_ENABLE_FTS3_PARENTHESIS ^
    -DSQLITE_ENABLE_FTS3_TOKENIZER ^
    -DSQLITE_ENABLE_FTS4 ^
    -DSQLITE_ENABLE_FTS5 ^
    -DSQLITE_ENABLE_GEOPOLY ^
    -DSQLITE_ENABLE_JSON1 ^
    -DSQLITE_ENABLE_MATH_FUNCTIONS ^
    -DSQLITE_ENABLE_PREUPDATE_HOOK ^
    -DSQLITE_ENABLE_RTREE ^
    -DSQLITE_ENABLE_SESSION ^
    -DSQLITE_ENABLE_STAT4 ^
    -DSQLITE_ENABLE_STMTVTAB ^
    -DSQLITE_ENABLE_UNLOCK_NOTIFY ^
    -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT ^
    -DSQLITE_LIKE_DOESNT_MATCH_BLOBS ^
    -DSQLITE_MAX_EXPR_DEPTH=10000 ^
    -DSQLITE_MAX_VARIABLE_NUMBER=250000 ^
    -DSQLITE_SECURE_DELETE ^
    -DSQLITE_SOUNDEX ^
    -DSQLITE_STRICT_SUBTYPE=1 ^
    -DSQLITE_THREADSAFE=1 ^
    -DSQLITE_USE_URI ^
    shell.c sqlite3.c -Fesqlite3.exe ^
    /DSQLITE_EXPORTS

:: build the dll
cl ^
    /O2 ^
    -DSQLITE_ENABLE_COLUMN_METADATA ^
    -DSQLITE_ENABLE_DBSTAT_VTAB ^
    -DSQLITE_ENABLE_DESERIALIZE ^
    -DSQLITE_ENABLE_EXPLAIN_COMMENTS ^
    -DSQLITE_ENABLE_FTS3 ^
    -DSQLITE_ENABLE_FTS3_PARENTHESIS ^
    -DSQLITE_ENABLE_FTS3_TOKENIZER ^
    -DSQLITE_ENABLE_FTS4 ^
    -DSQLITE_ENABLE_FTS5 ^
    -DSQLITE_ENABLE_GEOPOLY ^
    -DSQLITE_ENABLE_JSON1 ^
    -DSQLITE_ENABLE_MATH_FUNCTIONS ^
    -DSQLITE_ENABLE_PREUPDATE_HOOK ^
    -DSQLITE_ENABLE_RTREE ^
    -DSQLITE_ENABLE_SESSION ^
    -DSQLITE_ENABLE_STAT4 ^
    -DSQLITE_ENABLE_STMTVTAB ^
    -DSQLITE_ENABLE_UNLOCK_NOTIFY ^
    -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT ^
    -DSQLITE_LIKE_DOESNT_MATCH_BLOBS ^
    -DSQLITE_MAX_EXPR_DEPTH=10000 ^
    -DSQLITE_MAX_VARIABLE_NUMBER=250000 ^
    -DSQLITE_SECURE_DELETE ^
    -DSQLITE_SOUNDEX ^
    -DSQLITE_STRICT_SUBTYPE=1 ^
    -DSQLITE_THREADSAFE=1 ^
    -DSQLITE_USE_URI ^
    sqlite3.c -link -dll -out:sqlite3.dll

COPY sqlite3.exe  %LIBRARY_BIN% || exit 1
COPY sqlite3.dll  %LIBRARY_BIN% || exit 1
COPY sqlite3.lib  %LIBRARY_LIB% || exit 1
COPY sqlite3.h    %LIBRARY_INC% || exit 1
COPY sqlite3ext.h %LIBRARY_INC% || exit 1
