{% set version="3.13.0" %}
{% set year="2016" %}
{% set version_split=version.split(".") %}
{% set major=version_split[0] %}
{% set minor=version_split[1]|int * 10 %}
{% set bugfix=version_split[2]|int * 100 %}
{% set version_coded=(major ~ (("%03d" % minor)|string) ~ (("%03d" % bugfix)|string)) %}

package:
  name: sqlite
  version: {{ version }}

source:
  fn: sqlite-autoconf-{{ version_coded }}.tar.gz
  url: https://www.sqlite.org/{{ year }}/sqlite-autoconf-{{ version_coded }}.tar.gz
  sha256: e2797026b3310c9d08bd472f6d430058c6dd139ff9d4e30289884ccd9744086b
  patches:
    - expose_symbols.patch  # [win]

build:
  number: 1
  features:
    - vc9    # [win and py27]
    - vc10   # [win and py34]
    - vc14   # [win and py35]

requirements:
  build:
    # python is for lining up vc feature (runtime)
    - python      # [win]

test:
  requires:
    - python  2.7*     # [win and py27]
    - python  3.4*     # [win and py34]
    - python  3.5*     # [win and py35]
  commands:
    - sqlite3 --version
    - IF NOT EXIST %LIBRARY_BIN%\sqlite3.dll exit 1  # [win]
    - IF NOT EXIST %LIBRARY_LIB%\sqlite3.lib exit 1  # [win]
    - IF NOT EXIST %LIBRARY_INC%\sqlite3.h exit 1  # [win]

about:
  home: http://www.sqlite.org/
  license: Public-Domain (http://www.sqlite.org/copyright.html)
  license_family: Public-Domain
  summary: implements a self-contained, zero-configuration, SQL database engine

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
