{% set name = "sqlite" %}
{% set version = "3.24.0" %}
{% set ver_major = version.split(".")[0] %}
{% set ver_minor = version.split(".")[1] %}
{% set ver_patch = version.split(".")[2] %}
{% set ver_url = "".join([ver_major, ver_minor.ljust(3, "0"), ver_patch.ljust(3, "0")]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.sqlite.org/2018/{{ name }}-autoconf-{{ ver_url }}.tar.gz
  sha256: d9d14e88c6fb6d68de9ca0d1f9797477d82fc3aed613558f87ffbdbbc5ceb74a
  patches:
    - expose_symbols.patch  # [win]

build:
  number: 0

requirements:
  run:
    - {{ pin_subpackage(name|lower + '-' + sqlite_variant, exact=True) }}

test:
  commands:
    - sqlite3 --version
    - if not exist %PREFIX%\\Library\bin\sqlite3.dll exit 1    # [win]
    - if not exist %PREFIX%\\Library\lib\sqlite3.lib exit 1    # [win]
    - test -f $PREFIX/lib/libsqlite3.dylib                     # [osx]
    - test -f $PREFIX/lib/libsqlite3.so                        # [linux]
    - if not exist %PREFIX%\\Library\include\sqlite3.h exit 1  # [win]
    - test -f $PREFIX/include/sqlite3.h                        # [not win]

outputs:
  - name: _sqlite_variant
    build:
      string: {{ sqlite_variant }}
    version: {{ variant_version }}
    about:
      summary: "A package to specify the default sqlite variant."

  - name: {{ name|lower + '-' + sqlite_variant }}
    build:
      script:
        - bash $RECIPE_DIR/build_sqlite.sh --enable-editline --disable-readline  # [sqlite_variant == 'gplfree' and not win]
        - bash $RECIPE_DIR/build_sqlite.sh --enable-readline --disable-editline  # [sqlite_variant == 'readline']
        - "%RECIPE_DIR%\\build_sqlite.bat"  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - pkg-config  # [not win]
      host:
        - ncurses     # [not win]
        - readline    # [sqlite_variant == 'readline']
        - libedit     # [sqlite_variant == 'gplfree' and not win]
      run:
        - ncurses     # [not win]
        - readline    # [sqlite_variant == 'readline']
        - libedit     # [sqlite_variant == 'gplfree' and not win]
        - {{ pin_subpackage( "_sqlite_variant", exact=True) }}
    extra:
      sqlite_variant: {{ sqlite_variant }}

about:
  home: http://www.sqlite.org/
  license: Public-Domain (http://www.sqlite.org/copyright.html)
  summary: 'Implements a self-contained, zero-configuration, SQL database engine with libedit (gplfree) on unix machines.'  # [sqlite_variant == 'gplfree']
  summary: 'Implements a self-contained, zero-configuration, SQL database engine with readline support on unix machines.'   # [sqlite_variant == 'readline']

extra:
  sqlite_variant: {{ sqlite_variant }}
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - snorfalorpagus
