{% set name = "sqlite" %}
{% set version = "3.24.0" %}
{% set ver_major = version.split(".")[0] %}
{% set ver_minor = version.split(".")[1] %}
{% set ver_patch = version.split(".")[2] %}
{% set ver_url = "".join([ver_major, ver_minor.ljust(3, "0"), ver_patch.ljust(3, "0")]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.sqlite.org/2018/{{ name }}-autoconf-{{ ver_url }}.tar.gz
  sha256: d9d14e88c6fb6d68de9ca0d1f9797477d82fc3aed613558f87ffbdbbc5ceb74a
  patches:
    - expose_symbols.patch  # [win]

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config             # [not win]
  host:
    - ncurses                # [not win]
    - readline               # [not win]


outputs:
  - name: libsqlite
    files:
      - include/sqlite3*          # [not win]
      - share/man/man1/sqlite3*   # [not win]
      - lib/libsqlite3*           # [not win]
      - lib/pkgconfig/sqlite3.pc  # [not win]
      - Library/lib/sqlite3*      # [win]
      - Library/include/sqlite3*  # [win]
      - Library/bin/sqlite3.dll   # [win]
    requirements:
      - ncurses                   # [notwin]
    test:
      commands:
        - if not exist %PREFIX%\\Library\bin\sqlite3.dll exit 1    # [win]
        - if not exist %PREFIX%\\Library\lib\sqlite3.lib exit 1    # [win]
        - test -f $PREFIX/lib/libsqlite3.dylib                     # [osx]
        - test -f $PREFIX/lib/libsqlite3.so                        # [linux]
        - if not exist %PREFIX%\\Library\include\sqlite3.h exit 1  # [win]
        - test -f $PREFIX/include/sqlite3.h                        # [not win]
    about:
      home: http://www.sqlite.org/
      license: Public-Domain (http://www.sqlite.org/copyright.html)
      summary: 'Library for implementing a self-contained, zero-configuration, SQL database engine.'
  - name: sqlite
    files:
      - bin/sqlite3               # [not win]
      - Library/bin/sqlite3.exe   # [win]
    requirements:
      run:
        - {{ pin_subpackage("libsqlite", exact=true) }}
        - readline   # [notwin]
    test:
      commands:
        - sqlite3 --version
    about:
      home: http://www.sqlite.org/
      license: GPL-3.0  # [not win]
      license: Public-Domain (http://www.sqlite.org/copyright.html)  # [win]
      summary: 'Implements a self-contained, zero-configuration, SQL database engine.'

about:
  home: http://www.sqlite.org/
  license: GPLv3 or Public Domain
  summary: 'Implements a self-contained, zero-configuration, SQL database engine.'

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - snorfalorpagus
