{% set name = "sqlite" %}
{% set version = "3.25.0" %}
{% set ver_major = version.split(".")[0] %}
{% set ver_minor = version.split(".")[1] %}
{% set ver_patch = version.split(".")[2] %}
{% set ver_url = "".join([ver_major, ver_minor.ljust(3, "0"), ver_patch.ljust(3, "0")]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.sqlite.org/2018/{{ name }}-autoconf-{{ ver_url }}.tar.gz
  sha256: de1a93dfc1ea23d93ee85440fe4347d0b9cd936f25c29645ee0ee170d1307f71
  patches:
    - expose_symbols.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config             # [not win]
  host:
    - ncurses                # [not win]
    - readline               # [not win]
  run:
    - ncurses                # [not win]
    - readline               # [not win]

test:
  commands:
    - sqlite3 --version
    - if not exist %PREFIX%\\Library\bin\sqlite3.dll exit 1    # [win]
    - if not exist %PREFIX%\\Library\lib\sqlite3.lib exit 1    # [win]
    - test -f $PREFIX/lib/libsqlite3.dylib                     # [osx]
    - test -f $PREFIX/lib/libsqlite3.so                        # [linux]
    - if not exist %PREFIX%\\Library\include\sqlite3.h exit 1  # [win]
    - test -f $PREFIX/include/sqlite3.h                        # [not win]

about:
  home: http://www.sqlite.org/
  license: Public-Domain (http://www.sqlite.org/copyright.html)
  summary: 'Implements a self-contained, zero-configuration, SQL database engine.'

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - snorfalorpagus
